train_type_lookup = {
    "AB": "Amrit Bharat",
    "ACExp": "Mail / Express",
    "ACSF": "Superfast",
    "Ant": "Antyodaya",
    "Chn": "EMU",
    "DD": "AC Double Decker",
    "Del": "EMU",
    "DEMU": "DEMU",
    "Drnt": "Duronto",
    "Exp": "Express",
    "GR": "Garib Rath",
    "Hms": "Humsafar",
    "Hyd": "Hyderabad MMTS",
    "JShtb": "Jan Shatabdi",
    "Klkt": "EMU",
    "MEMU": "MEMU",
    "Mumb": "EMU",
    "NB": "Namo Bharat",
    "Pass": "Passenger",
    "Pune": "EMU",    
    "Raj": "Rajdhani",
    "SF": "Superfast",
    "Shtb": "Shatabdi",
    "SKr": "Sampark Kranti",
    "Tjs": "Tejas",
    "Toy": "Toy Train",
    "Udy": "Uday Exp",
    "VB": "Vande Bharat"    
}

train_type_lookup_unreserved = {
    "AB": "Amrit Bharat",
    "ACExp": "Mail / Express",
    "ACSF": "Superfast",
    "Ant": "Antyodaya",
    "Chn": "Chennai EMU",
    "DD": "AC Double Decker",
    "Del": "Delhi EMU",
    "DEMU": "DEMU",
    "Drnt": "Duronto",
    "Exp": "Express",
    "GR": "Garib Rath",
    "Hms": "Humsafar",
    "Hyd": "Hyderabad MMTS",
    "JShtb": "Jan Shatabdi",
    "Klkt": "Kolkata EMU",
    "MEMU": "MEMU",
    "Mumb": "Mumbai EMU",
    "NB": "Namo Bharat",
    "Pass": "Passenger",
    "Pune": "Pune EMU",    
    "Raj": "Rajdhani",
    "SF": "Superfast",
    "Shtb": "Shatabdi",
    "SKr": "Sampark Kranti",
    "Tjs": "Tejas",
    "Toy": "Toy Train",
    "Udy": "Uday Exp",
    "VB": "Vande Bharat"    
}